srcdir = "."
blddir = "build"

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")
  conf.find_program('node', var='NODE', mandatory=True)
  if conf.check_cc(header_name="sys/inotify.h"):
    conf.check_cc(header_name="linux/inotify.h", function_name="inotify_init")

def build(bld):
  obj = bld.new_task_gen("cxx", "shlib", "node_addon")
  obj.target = "node-inotify"
  obj.source = bld.path.ant_glob('**/*.cc')

